// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: keyvalue.proto
#ifndef GRPC_keyvalue_2eproto__INCLUDED
#define GRPC_keyvalue_2eproto__INCLUDED

#include "keyvalue.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace keyvalue {

class KVStore final {
 public:
  static constexpr char const* service_full_name() {
    return "keyvalue.KVStore";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::keyvalue::KeyValueReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>> AsyncGetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>>(AsyncGetKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>> PrepareAsyncGetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>>(PrepareAsyncGetKeyRaw(context, request, cq));
    }
    virtual ::grpc::Status PutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::keyvalue::KeyValueReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>> AsyncPutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>>(AsyncPutKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>> PrepareAsyncPutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>>(PrepareAsyncPutKeyRaw(context, request, cq));
    }
    virtual ::grpc::Status DeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::keyvalue::KeyValueReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>> AsyncDeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>>(AsyncDeleteKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>> PrepareAsyncDeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>>(PrepareAsyncDeleteKeyRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void PutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest* request, ::keyvalue::KeyValueReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest* request, ::keyvalue::KeyValueReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void DeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>* AsyncGetKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>* PrepareAsyncGetKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>* AsyncPutKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>* PrepareAsyncPutKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>* AsyncDeleteKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>* PrepareAsyncDeleteKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::keyvalue::KeyValueReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>> AsyncGetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>>(AsyncGetKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>> PrepareAsyncGetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>>(PrepareAsyncGetKeyRaw(context, request, cq));
    }
    ::grpc::Status PutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::keyvalue::KeyValueReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>> AsyncPutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>>(AsyncPutKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>> PrepareAsyncPutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>>(PrepareAsyncPutKeyRaw(context, request, cq));
    }
    ::grpc::Status DeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::keyvalue::KeyValueReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>> AsyncDeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>>(AsyncDeleteKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>> PrepareAsyncDeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>>(PrepareAsyncDeleteKeyRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response, std::function<void(::grpc::Status)>) override;
      void GetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void PutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest* request, ::keyvalue::KeyValueReply* response, std::function<void(::grpc::Status)>) override;
      void PutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest* request, ::keyvalue::KeyValueReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response, std::function<void(::grpc::Status)>) override;
      void DeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>* AsyncGetKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>* PrepareAsyncGetKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>* AsyncPutKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>* PrepareAsyncPutKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>* AsyncDeleteKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>* PrepareAsyncDeleteKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetKey_;
    const ::grpc::internal::RpcMethod rpcmethod_PutKey_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteKey_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetKey(::grpc::ServerContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response);
    virtual ::grpc::Status PutKey(::grpc::ServerContext* context, const ::keyvalue::KeyValueRequest* request, ::keyvalue::KeyValueReply* response);
    virtual ::grpc::Status DeleteKey(::grpc::ServerContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetKey() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetKey(::grpc::ServerContext* context, ::keyvalue::KeyRequest* request, ::grpc::ServerAsyncResponseWriter< ::keyvalue::KeyValueReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PutKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PutKey() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_PutKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyValueRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPutKey(::grpc::ServerContext* context, ::keyvalue::KeyValueRequest* request, ::grpc::ServerAsyncResponseWriter< ::keyvalue::KeyValueReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeleteKey() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_DeleteKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteKey(::grpc::ServerContext* context, ::keyvalue::KeyRequest* request, ::grpc::ServerAsyncResponseWriter< ::keyvalue::KeyValueReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetKey<WithAsyncMethod_PutKey<WithAsyncMethod_DeleteKey<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetKey() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response) { return this->GetKey(context, request, response); }));}
    void SetMessageAllocatorFor_GetKey(
        ::grpc::MessageAllocator< ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetKey(
      ::grpc::CallbackServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_PutKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PutKey() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::keyvalue::KeyValueRequest, ::keyvalue::KeyValueReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::keyvalue::KeyValueRequest* request, ::keyvalue::KeyValueReply* response) { return this->PutKey(context, request, response); }));}
    void SetMessageAllocatorFor_PutKey(
        ::grpc::MessageAllocator< ::keyvalue::KeyValueRequest, ::keyvalue::KeyValueReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::keyvalue::KeyValueRequest, ::keyvalue::KeyValueReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PutKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyValueRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PutKey(
      ::grpc::CallbackServerContext* /*context*/, const ::keyvalue::KeyValueRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DeleteKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DeleteKey() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response) { return this->DeleteKey(context, request, response); }));}
    void SetMessageAllocatorFor_DeleteKey(
        ::grpc::MessageAllocator< ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DeleteKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteKey(
      ::grpc::CallbackServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetKey<WithCallbackMethod_PutKey<WithCallbackMethod_DeleteKey<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetKey() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PutKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PutKey() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_PutKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyValueRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeleteKey() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_DeleteKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetKey() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetKey(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PutKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PutKey() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_PutKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyValueRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPutKey(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeleteKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeleteKey() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_DeleteKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteKey(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetKey() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetKey(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetKey(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PutKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PutKey() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PutKey(context, request, response); }));
    }
    ~WithRawCallbackMethod_PutKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyValueRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PutKey(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DeleteKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DeleteKey() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeleteKey(context, request, response); }));
    }
    ~WithRawCallbackMethod_DeleteKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteKey(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetKey() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>* streamer) {
                       return this->StreamedGetKey(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetKey(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::keyvalue::KeyRequest,::keyvalue::KeyValueReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PutKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PutKey() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::keyvalue::KeyValueRequest, ::keyvalue::KeyValueReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::keyvalue::KeyValueRequest, ::keyvalue::KeyValueReply>* streamer) {
                       return this->StreamedPutKey(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PutKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PutKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyValueRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPutKey(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::keyvalue::KeyValueRequest,::keyvalue::KeyValueReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeleteKey() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>* streamer) {
                       return this->StreamedDeleteKey(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeleteKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteKey(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::keyvalue::KeyRequest,::keyvalue::KeyValueReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetKey<WithStreamedUnaryMethod_PutKey<WithStreamedUnaryMethod_DeleteKey<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetKey<WithStreamedUnaryMethod_PutKey<WithStreamedUnaryMethod_DeleteKey<Service > > > StreamedService;
};

}  // namespace keyvalue


#endif  // GRPC_keyvalue_2eproto__INCLUDED
