// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: keyvalue.proto
#ifndef GRPC_keyvalue_2eproto__INCLUDED
#define GRPC_keyvalue_2eproto__INCLUDED

#include "keyvalue.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace keyvalue {

class KVStore final {
 public:
  static constexpr char const* service_full_name() {
    return "keyvalue.KVStore";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::keyvalue::KeyValueReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>> AsyncGetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>>(AsyncGetKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>> PrepareAsyncGetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>>(PrepareAsyncGetKeyRaw(context, request, cq));
    }
    virtual ::grpc::Status PutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::keyvalue::KeyValueReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>> AsyncPutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>>(AsyncPutKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>> PrepareAsyncPutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>>(PrepareAsyncPutKeyRaw(context, request, cq));
    }
    virtual ::grpc::Status DeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::keyvalue::KeyValueReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>> AsyncDeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>>(AsyncDeleteKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>> PrepareAsyncDeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>>(PrepareAsyncDeleteKeyRaw(context, request, cq));
    }
    virtual ::grpc::Status DistMethod(::grpc::ClientContext* context, const ::keyvalue::DistRequest& request, ::keyvalue::DistReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::DistReply>> AsyncDistMethod(::grpc::ClientContext* context, const ::keyvalue::DistRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::DistReply>>(AsyncDistMethodRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::DistReply>> PrepareAsyncDistMethod(::grpc::ClientContext* context, const ::keyvalue::DistRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::DistReply>>(PrepareAsyncDistMethodRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void PutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest* request, ::keyvalue::KeyValueReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest* request, ::keyvalue::KeyValueReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void DeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void DistMethod(::grpc::ClientContext* context, const ::keyvalue::DistRequest* request, ::keyvalue::DistReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DistMethod(::grpc::ClientContext* context, const ::keyvalue::DistRequest* request, ::keyvalue::DistReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>* AsyncGetKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>* PrepareAsyncGetKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>* AsyncPutKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>* PrepareAsyncPutKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>* AsyncDeleteKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::KeyValueReply>* PrepareAsyncDeleteKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::DistReply>* AsyncDistMethodRaw(::grpc::ClientContext* context, const ::keyvalue::DistRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::DistReply>* PrepareAsyncDistMethodRaw(::grpc::ClientContext* context, const ::keyvalue::DistRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::keyvalue::KeyValueReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>> AsyncGetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>>(AsyncGetKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>> PrepareAsyncGetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>>(PrepareAsyncGetKeyRaw(context, request, cq));
    }
    ::grpc::Status PutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::keyvalue::KeyValueReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>> AsyncPutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>>(AsyncPutKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>> PrepareAsyncPutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>>(PrepareAsyncPutKeyRaw(context, request, cq));
    }
    ::grpc::Status DeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::keyvalue::KeyValueReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>> AsyncDeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>>(AsyncDeleteKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>> PrepareAsyncDeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>>(PrepareAsyncDeleteKeyRaw(context, request, cq));
    }
    ::grpc::Status DistMethod(::grpc::ClientContext* context, const ::keyvalue::DistRequest& request, ::keyvalue::DistReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::DistReply>> AsyncDistMethod(::grpc::ClientContext* context, const ::keyvalue::DistRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::DistReply>>(AsyncDistMethodRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::DistReply>> PrepareAsyncDistMethod(::grpc::ClientContext* context, const ::keyvalue::DistRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::DistReply>>(PrepareAsyncDistMethodRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response, std::function<void(::grpc::Status)>) override;
      void GetKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void PutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest* request, ::keyvalue::KeyValueReply* response, std::function<void(::grpc::Status)>) override;
      void PutKey(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest* request, ::keyvalue::KeyValueReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response, std::function<void(::grpc::Status)>) override;
      void DeleteKey(::grpc::ClientContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DistMethod(::grpc::ClientContext* context, const ::keyvalue::DistRequest* request, ::keyvalue::DistReply* response, std::function<void(::grpc::Status)>) override;
      void DistMethod(::grpc::ClientContext* context, const ::keyvalue::DistRequest* request, ::keyvalue::DistReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>* AsyncGetKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>* PrepareAsyncGetKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>* AsyncPutKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>* PrepareAsyncPutKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyValueRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>* AsyncDeleteKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::keyvalue::KeyValueReply>* PrepareAsyncDeleteKeyRaw(::grpc::ClientContext* context, const ::keyvalue::KeyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::keyvalue::DistReply>* AsyncDistMethodRaw(::grpc::ClientContext* context, const ::keyvalue::DistRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::keyvalue::DistReply>* PrepareAsyncDistMethodRaw(::grpc::ClientContext* context, const ::keyvalue::DistRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetKey_;
    const ::grpc::internal::RpcMethod rpcmethod_PutKey_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteKey_;
    const ::grpc::internal::RpcMethod rpcmethod_DistMethod_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetKey(::grpc::ServerContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response);
    virtual ::grpc::Status PutKey(::grpc::ServerContext* context, const ::keyvalue::KeyValueRequest* request, ::keyvalue::KeyValueReply* response);
    virtual ::grpc::Status DeleteKey(::grpc::ServerContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response);
    virtual ::grpc::Status DistMethod(::grpc::ServerContext* context, const ::keyvalue::DistRequest* request, ::keyvalue::DistReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetKey() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetKey(::grpc::ServerContext* context, ::keyvalue::KeyRequest* request, ::grpc::ServerAsyncResponseWriter< ::keyvalue::KeyValueReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PutKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PutKey() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_PutKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyValueRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPutKey(::grpc::ServerContext* context, ::keyvalue::KeyValueRequest* request, ::grpc::ServerAsyncResponseWriter< ::keyvalue::KeyValueReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeleteKey() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_DeleteKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteKey(::grpc::ServerContext* context, ::keyvalue::KeyRequest* request, ::grpc::ServerAsyncResponseWriter< ::keyvalue::KeyValueReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DistMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DistMethod() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_DistMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DistMethod(::grpc::ServerContext* /*context*/, const ::keyvalue::DistRequest* /*request*/, ::keyvalue::DistReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDistMethod(::grpc::ServerContext* context, ::keyvalue::DistRequest* request, ::grpc::ServerAsyncResponseWriter< ::keyvalue::DistReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetKey<WithAsyncMethod_PutKey<WithAsyncMethod_DeleteKey<WithAsyncMethod_DistMethod<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetKey() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response) { return this->GetKey(context, request, response); }));}
    void SetMessageAllocatorFor_GetKey(
        ::grpc::MessageAllocator< ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetKey(
      ::grpc::CallbackServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_PutKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PutKey() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::keyvalue::KeyValueRequest, ::keyvalue::KeyValueReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::keyvalue::KeyValueRequest* request, ::keyvalue::KeyValueReply* response) { return this->PutKey(context, request, response); }));}
    void SetMessageAllocatorFor_PutKey(
        ::grpc::MessageAllocator< ::keyvalue::KeyValueRequest, ::keyvalue::KeyValueReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::keyvalue::KeyValueRequest, ::keyvalue::KeyValueReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PutKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyValueRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PutKey(
      ::grpc::CallbackServerContext* /*context*/, const ::keyvalue::KeyValueRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DeleteKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DeleteKey() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::keyvalue::KeyRequest* request, ::keyvalue::KeyValueReply* response) { return this->DeleteKey(context, request, response); }));}
    void SetMessageAllocatorFor_DeleteKey(
        ::grpc::MessageAllocator< ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DeleteKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteKey(
      ::grpc::CallbackServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DistMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DistMethod() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::keyvalue::DistRequest, ::keyvalue::DistReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::keyvalue::DistRequest* request, ::keyvalue::DistReply* response) { return this->DistMethod(context, request, response); }));}
    void SetMessageAllocatorFor_DistMethod(
        ::grpc::MessageAllocator< ::keyvalue::DistRequest, ::keyvalue::DistReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::keyvalue::DistRequest, ::keyvalue::DistReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DistMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DistMethod(::grpc::ServerContext* /*context*/, const ::keyvalue::DistRequest* /*request*/, ::keyvalue::DistReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DistMethod(
      ::grpc::CallbackServerContext* /*context*/, const ::keyvalue::DistRequest* /*request*/, ::keyvalue::DistReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetKey<WithCallbackMethod_PutKey<WithCallbackMethod_DeleteKey<WithCallbackMethod_DistMethod<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetKey() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PutKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PutKey() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_PutKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyValueRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeleteKey() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_DeleteKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DistMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DistMethod() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_DistMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DistMethod(::grpc::ServerContext* /*context*/, const ::keyvalue::DistRequest* /*request*/, ::keyvalue::DistReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetKey() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetKey(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PutKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PutKey() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_PutKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyValueRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPutKey(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeleteKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeleteKey() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_DeleteKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteKey(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DistMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DistMethod() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_DistMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DistMethod(::grpc::ServerContext* /*context*/, const ::keyvalue::DistRequest* /*request*/, ::keyvalue::DistReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDistMethod(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetKey() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetKey(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetKey(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PutKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PutKey() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PutKey(context, request, response); }));
    }
    ~WithRawCallbackMethod_PutKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PutKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyValueRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PutKey(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DeleteKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DeleteKey() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeleteKey(context, request, response); }));
    }
    ~WithRawCallbackMethod_DeleteKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteKey(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DistMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DistMethod() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DistMethod(context, request, response); }));
    }
    ~WithRawCallbackMethod_DistMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DistMethod(::grpc::ServerContext* /*context*/, const ::keyvalue::DistRequest* /*request*/, ::keyvalue::DistReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DistMethod(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetKey() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>* streamer) {
                       return this->StreamedGetKey(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetKey(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::keyvalue::KeyRequest,::keyvalue::KeyValueReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PutKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PutKey() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::keyvalue::KeyValueRequest, ::keyvalue::KeyValueReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::keyvalue::KeyValueRequest, ::keyvalue::KeyValueReply>* streamer) {
                       return this->StreamedPutKey(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PutKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PutKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyValueRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPutKey(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::keyvalue::KeyValueRequest,::keyvalue::KeyValueReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeleteKey() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::keyvalue::KeyRequest, ::keyvalue::KeyValueReply>* streamer) {
                       return this->StreamedDeleteKey(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeleteKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteKey(::grpc::ServerContext* /*context*/, const ::keyvalue::KeyRequest* /*request*/, ::keyvalue::KeyValueReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteKey(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::keyvalue::KeyRequest,::keyvalue::KeyValueReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DistMethod : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DistMethod() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::keyvalue::DistRequest, ::keyvalue::DistReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::keyvalue::DistRequest, ::keyvalue::DistReply>* streamer) {
                       return this->StreamedDistMethod(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DistMethod() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DistMethod(::grpc::ServerContext* /*context*/, const ::keyvalue::DistRequest* /*request*/, ::keyvalue::DistReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDistMethod(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::keyvalue::DistRequest,::keyvalue::DistReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetKey<WithStreamedUnaryMethod_PutKey<WithStreamedUnaryMethod_DeleteKey<WithStreamedUnaryMethod_DistMethod<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetKey<WithStreamedUnaryMethod_PutKey<WithStreamedUnaryMethod_DeleteKey<WithStreamedUnaryMethod_DistMethod<Service > > > > StreamedService;
};

class ServerComm final {
 public:
  static constexpr char const* service_full_name() {
    return "keyvalue.ServerComm";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Join(::grpc::ClientContext* context, const ::keyvalue::JoinRequest& request, ::keyvalue::JoinReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::JoinReply>> AsyncJoin(::grpc::ClientContext* context, const ::keyvalue::JoinRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::JoinReply>>(AsyncJoinRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::JoinReply>> PrepareAsyncJoin(::grpc::ClientContext* context, const ::keyvalue::JoinRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::JoinReply>>(PrepareAsyncJoinRaw(context, request, cq));
    }
    virtual ::grpc::Status Share_key(::grpc::ClientContext* context, const ::keyvalue::IdPortMessage& request, ::keyvalue::IdResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::IdResponse>> AsyncShare_key(::grpc::ClientContext* context, const ::keyvalue::IdPortMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::IdResponse>>(AsyncShare_keyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::IdResponse>> PrepareAsyncShare_key(::grpc::ClientContext* context, const ::keyvalue::IdPortMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::IdResponse>>(PrepareAsyncShare_keyRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Join(::grpc::ClientContext* context, const ::keyvalue::JoinRequest* request, ::keyvalue::JoinReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Join(::grpc::ClientContext* context, const ::keyvalue::JoinRequest* request, ::keyvalue::JoinReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Share_key(::grpc::ClientContext* context, const ::keyvalue::IdPortMessage* request, ::keyvalue::IdResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Share_key(::grpc::ClientContext* context, const ::keyvalue::IdPortMessage* request, ::keyvalue::IdResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::JoinReply>* AsyncJoinRaw(::grpc::ClientContext* context, const ::keyvalue::JoinRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::JoinReply>* PrepareAsyncJoinRaw(::grpc::ClientContext* context, const ::keyvalue::JoinRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::IdResponse>* AsyncShare_keyRaw(::grpc::ClientContext* context, const ::keyvalue::IdPortMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::keyvalue::IdResponse>* PrepareAsyncShare_keyRaw(::grpc::ClientContext* context, const ::keyvalue::IdPortMessage& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Join(::grpc::ClientContext* context, const ::keyvalue::JoinRequest& request, ::keyvalue::JoinReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::JoinReply>> AsyncJoin(::grpc::ClientContext* context, const ::keyvalue::JoinRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::JoinReply>>(AsyncJoinRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::JoinReply>> PrepareAsyncJoin(::grpc::ClientContext* context, const ::keyvalue::JoinRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::JoinReply>>(PrepareAsyncJoinRaw(context, request, cq));
    }
    ::grpc::Status Share_key(::grpc::ClientContext* context, const ::keyvalue::IdPortMessage& request, ::keyvalue::IdResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::IdResponse>> AsyncShare_key(::grpc::ClientContext* context, const ::keyvalue::IdPortMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::IdResponse>>(AsyncShare_keyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::IdResponse>> PrepareAsyncShare_key(::grpc::ClientContext* context, const ::keyvalue::IdPortMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::keyvalue::IdResponse>>(PrepareAsyncShare_keyRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Join(::grpc::ClientContext* context, const ::keyvalue::JoinRequest* request, ::keyvalue::JoinReply* response, std::function<void(::grpc::Status)>) override;
      void Join(::grpc::ClientContext* context, const ::keyvalue::JoinRequest* request, ::keyvalue::JoinReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Share_key(::grpc::ClientContext* context, const ::keyvalue::IdPortMessage* request, ::keyvalue::IdResponse* response, std::function<void(::grpc::Status)>) override;
      void Share_key(::grpc::ClientContext* context, const ::keyvalue::IdPortMessage* request, ::keyvalue::IdResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::keyvalue::JoinReply>* AsyncJoinRaw(::grpc::ClientContext* context, const ::keyvalue::JoinRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::keyvalue::JoinReply>* PrepareAsyncJoinRaw(::grpc::ClientContext* context, const ::keyvalue::JoinRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::keyvalue::IdResponse>* AsyncShare_keyRaw(::grpc::ClientContext* context, const ::keyvalue::IdPortMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::keyvalue::IdResponse>* PrepareAsyncShare_keyRaw(::grpc::ClientContext* context, const ::keyvalue::IdPortMessage& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Join_;
    const ::grpc::internal::RpcMethod rpcmethod_Share_key_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Join(::grpc::ServerContext* context, const ::keyvalue::JoinRequest* request, ::keyvalue::JoinReply* response);
    virtual ::grpc::Status Share_key(::grpc::ServerContext* context, const ::keyvalue::IdPortMessage* request, ::keyvalue::IdResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Join : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Join() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Join() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Join(::grpc::ServerContext* /*context*/, const ::keyvalue::JoinRequest* /*request*/, ::keyvalue::JoinReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestJoin(::grpc::ServerContext* context, ::keyvalue::JoinRequest* request, ::grpc::ServerAsyncResponseWriter< ::keyvalue::JoinReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Share_key : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Share_key() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Share_key() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Share_key(::grpc::ServerContext* /*context*/, const ::keyvalue::IdPortMessage* /*request*/, ::keyvalue::IdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestShare_key(::grpc::ServerContext* context, ::keyvalue::IdPortMessage* request, ::grpc::ServerAsyncResponseWriter< ::keyvalue::IdResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Join<WithAsyncMethod_Share_key<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Join : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Join() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::keyvalue::JoinRequest, ::keyvalue::JoinReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::keyvalue::JoinRequest* request, ::keyvalue::JoinReply* response) { return this->Join(context, request, response); }));}
    void SetMessageAllocatorFor_Join(
        ::grpc::MessageAllocator< ::keyvalue::JoinRequest, ::keyvalue::JoinReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::keyvalue::JoinRequest, ::keyvalue::JoinReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Join() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Join(::grpc::ServerContext* /*context*/, const ::keyvalue::JoinRequest* /*request*/, ::keyvalue::JoinReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Join(
      ::grpc::CallbackServerContext* /*context*/, const ::keyvalue::JoinRequest* /*request*/, ::keyvalue::JoinReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Share_key : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Share_key() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::keyvalue::IdPortMessage, ::keyvalue::IdResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::keyvalue::IdPortMessage* request, ::keyvalue::IdResponse* response) { return this->Share_key(context, request, response); }));}
    void SetMessageAllocatorFor_Share_key(
        ::grpc::MessageAllocator< ::keyvalue::IdPortMessage, ::keyvalue::IdResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::keyvalue::IdPortMessage, ::keyvalue::IdResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Share_key() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Share_key(::grpc::ServerContext* /*context*/, const ::keyvalue::IdPortMessage* /*request*/, ::keyvalue::IdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Share_key(
      ::grpc::CallbackServerContext* /*context*/, const ::keyvalue::IdPortMessage* /*request*/, ::keyvalue::IdResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Join<WithCallbackMethod_Share_key<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Join : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Join() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Join() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Join(::grpc::ServerContext* /*context*/, const ::keyvalue::JoinRequest* /*request*/, ::keyvalue::JoinReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Share_key : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Share_key() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Share_key() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Share_key(::grpc::ServerContext* /*context*/, const ::keyvalue::IdPortMessage* /*request*/, ::keyvalue::IdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Join : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Join() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Join() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Join(::grpc::ServerContext* /*context*/, const ::keyvalue::JoinRequest* /*request*/, ::keyvalue::JoinReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestJoin(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Share_key : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Share_key() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Share_key() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Share_key(::grpc::ServerContext* /*context*/, const ::keyvalue::IdPortMessage* /*request*/, ::keyvalue::IdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestShare_key(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Join : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Join() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Join(context, request, response); }));
    }
    ~WithRawCallbackMethod_Join() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Join(::grpc::ServerContext* /*context*/, const ::keyvalue::JoinRequest* /*request*/, ::keyvalue::JoinReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Join(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Share_key : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Share_key() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Share_key(context, request, response); }));
    }
    ~WithRawCallbackMethod_Share_key() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Share_key(::grpc::ServerContext* /*context*/, const ::keyvalue::IdPortMessage* /*request*/, ::keyvalue::IdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Share_key(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Join : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Join() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::keyvalue::JoinRequest, ::keyvalue::JoinReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::keyvalue::JoinRequest, ::keyvalue::JoinReply>* streamer) {
                       return this->StreamedJoin(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Join() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Join(::grpc::ServerContext* /*context*/, const ::keyvalue::JoinRequest* /*request*/, ::keyvalue::JoinReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedJoin(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::keyvalue::JoinRequest,::keyvalue::JoinReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Share_key : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Share_key() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::keyvalue::IdPortMessage, ::keyvalue::IdResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::keyvalue::IdPortMessage, ::keyvalue::IdResponse>* streamer) {
                       return this->StreamedShare_key(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Share_key() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Share_key(::grpc::ServerContext* /*context*/, const ::keyvalue::IdPortMessage* /*request*/, ::keyvalue::IdResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedShare_key(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::keyvalue::IdPortMessage,::keyvalue::IdResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Join<WithStreamedUnaryMethod_Share_key<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Join<WithStreamedUnaryMethod_Share_key<Service > > StreamedService;
};

}  // namespace keyvalue


#endif  // GRPC_keyvalue_2eproto__INCLUDED
